Correct NTPd package choosing under el9
sous-chefs/ntp pull request #253
Opened 2024-07-12 14:44 UTC by bish0polis

# Description

Making the jump from EL7 to EL9, I noticed the name of the package that delivers ntpd and ntpdate is now from the ntpsec project via EPEL9.

## Issues Resolved

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

Cannot test:  Will not run Chef15+ due to licensing trapdoor; but code tests well in 14.15.6/el9 .

2024-07-12 14:49 UTC, bish0polis commented
I'm not sure what the rel-label validator wants.  sio sarakasi yangu.

2024-07-15 14:42 UTC, Stromweld requested changes

2024-07-15 14:42 UTC, Stromweld commented on attributes/default.rb
> +  default['ntp']['packages'] = %w(ntpsec)      if node['platform_version'].to_i >= 9
```suggestion
  default['ntp']['packages'] = if node['platform_version'].to_i >= 9
                                                    %w(ntpsec) # RPM found in Epel Repo
                                                  else
                                                    %w(ntp ntpdate)
                                                  end  
```

2024-07-15 20:48 UTC, Stromweld approved these changes

2024-07-15 20:48 UTC, merged

2024-07-15 20:48 UTC, kitchen-porter commented
Released as: [5.2.2](https://github.com/sous-chefs/ntp/releases/tag/5.2.2)